{
 "title": "AGL XDS Supervisor",
 "time": { "from": "2018-06-14T15:03:47.885Z", "to": "2018-06-14T15:04:03.173Z" },
 "panels": [
  {
   "title": "Number of Traces",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "xds/supervisor/trace",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests & Events per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Events",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "xds/supervisor/trace",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"supervisor/trace\" WHERE (\"tag\" = 'xds:*/event') AND time > now() - time($__interval) GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "event" }
     ]
    },
    {
     "alias": "Requests",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "xds/supervisor/trace",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"supervisor/trace\" WHERE (\"tag\" = 'xds:*/event') AND time > now() - time($__interval) GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "request" }
     ]
    }
   ]
  },
  {
   "title": "Events Data bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "xds/supervisor/trace",
     "query": "SELECT \"data_bytes\" FROM \"supervisor/trace\" WHERE (\"tag\" = 'xds:*/event') AND $timeFilter",
     "select": [
      [
       { "params": [ "data_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "event" }
     ]
    }
   ]
  },
  {
   "title": "Nb Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "xds/supervisor/trace",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "request" }
     ]
    }
   ]
  },
  {
   "title": "Nb Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "xds/supervisor/trace",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "event" }
     ]
    }
   ]
  },
  {
   "title": "Supervisor traces table",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "xds/supervisor/trace",
     "query": "SELECT \"id\", \"req_index\",  \"api\", \"verb\", \"name\", \"tag\", \"session\", \"data\", \"data_bytes\", \"index_id\" FROM \"supervisor/trace\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "id" ], "type": "field" }
      ],
      [
       { "params": [ "req_index" ], "type": "field" }
      ],
      [
       { "params": [ "api" ], "type": "field" }
      ],
      [
       { "params": [ "verb" ], "type": "field" }
      ],
      [
       { "params": [ "action" ], "type": "field" }
      ],
      [
       { "params": [ "name" ], "type": "field" }
      ],
      [
       { "params": [ "type" ], "type": "field" }
      ],
      [
       { "params": [ "session" ], "type": "field" }
      ],
      [
       { "params": [ "data" ], "type": "field" }
      ],
      [
       { "params": [ "data_bytes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "measurement": "supervisor/trace",
     "query": "SELECT \"action\", \"id\", \"api\", \"verb\", \"name\", \"session\", \"req_index\" FROM \"xds/supervisor/trace\" WHERE (\"type\" = 'request') AND $timeFilter",
     "select": [
      [
       { "params": [ "action" ], "type": "field" }
      ],
      [
       { "params": [ "id" ], "type": "field" }
      ],
      [
       { "params": [ "api" ], "type": "field" }
      ],
      [
       { "params": [ "verb" ], "type": "field" }
      ],
      [
       { "params": [ "name" ], "type": "field" }
      ],
      [
       { "params": [ "session" ], "type": "field" }
      ],
      [
       { "params": [ "req_index" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "xds:*/request" }
     ]
    }
   ]
  }
 ]
}